version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.8.1
    - 1.9.1
